--- #YAML:1.0
name:                Device-Velleman-PPS10
version:             0.02
abstract:            Read data from Velleman PPS10 oscilloscope
license:             ~
author:              
    - Narbey Derbekyan <narbey@localdomain>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Device::SerialPort:            1.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
